name       : rawstudio
version    : 2.0
release    : 10
source     :
    - git|https://github.com/rawstudio/rawstudio.git : 003dd4f33377dcfd15ae32904a7cbb0e92123607
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Rawstudio is an open-source program to read and manipulate RAW images from digital cameras.
description: |
    To get the best quality out of your digital camera, it is often recommended that you record your pictures in RAW format. This format is mostly specific to a camera and cannot be read by most image editing applications. Our goal is to supply you with a tool, where you can have the benefits of RAW images and the ease of use of JPEG images.
    The main focus of Rawstudio is to enable efficient review and fast processing of large image collections. We aim to supply you with a tool that makes it possible for you to review and process several hundred images in a matter of a few hours.
    Rawstudio will convert your RAW files into JPEG, PNG or TIF images which you can then print or send to friends and clients.
    Rawstudio is intended as the first tool in your image processing chain. After you have made your overall image adjustments to your image, you can use an image editing application to further work on your images. Rawstudio itself is a highly specialized application for reviewing and processing RAW images, not a fully featured image editing application.
libsplit   : no
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(fftw3f)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libjpeg)
    - pkgconfig(lcms2)
    - pkgconfig(lensfun)
    - pkgconfig(libcurl)
    - pkgconfig(libgphoto2)
    - pkgconfig(libtiff-4)
    - pkgconfig(sqlite3)
    - pkgconfig(x11)
setup      : |
    %apply_patches
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
